[workspace]
resolver = "2"

members = [
    "p4",
    "x4c",
    "x4c_error_codes",
    "codegen/rust",
    "lang/p4rs",
    "lang/p4-macro",
    "lang/p4-macro-test",
    "lang/prog/sidecar-lite",
    "test",
    "book/code",
]

[workspace.dependencies]
usdt = "0.3.5"
