= P4

This repository contains a P4 toolchain. The toolchain includes.

- A Rust library crate for lexing, parsing and checking P4 code.
- Code generation for:
  - [x] Rust.
  - [ ] Docs a la `cargo doc`.
  - [ ] RedHawk/RISC-V
- A command-line P4 compiler called `x4c`.
- Macros for using P4 directly from Rust.


== Usage

=== CLI compilation

The primary artifact of this repository is the `x4c` compiler. This is a
multi-target compiler that takes P4 programs as input and can produce executable
code for a number of target backend platforms. The precise format and interfaces
for the code that gets generated by `x4c` depends on the targeet type.

The CLI interface can be used like a normal compiler. When using the Rust
target, the generated code will implement the `Pipeline` interface that is
suitable for placing on packet i/o paths for processing.

----
$ ./target/debug/x4c --help
x4c 0.1

USAGE:
    x4c [OPTIONS] <FILENAME> [TARGET]

ARGS:
    <FILENAME>    File to compile
    <TARGET>      What target to generate code for [default: rust] [possible values: rust,
                  red-hawk, docs]

OPTIONS:
        --check          Just check code, do not compile
    -h, --help           Print help information
    -o, --out <OUT>      Filename to write generated code to [default: out.rs]
        --show-ast       Show parsed abstract syntax tree
        --show-hlir      Show high-level intermediate representation info
        --show-pre       Show parsed preprocessor info
        --show-tokens    Show parsed lexical tokens
    -V, --version        Print version information
----

== Target Backends

- https://github.com/oxidecomputer/p4/blob/main/doc/rust.adoc[Rust]
