[package]
name = "x4c"
version = "0.1.0"
edition = "2021"

[dependencies]
colored.workspace = true
clap.workspace = true
anyhow.workspace = true
regex.workspace = true
p4.workspace = true
p4-rust.workspace = true
