[package]
name = "x4c"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
clap = { version = "3", features = ["color", "derive"] }
anyhow = "1"
p4 = { path = "../p4" }
p4-rust = { path = "../codegen/rust" }
