[package]
name = "sidecar-lite"
version = "0.1.0"
edition = "2021"

[lib]
name = "sidecar_lite"
crate-type = ["dylib"]

[dependencies]
p4rs.workspace = true
p4-macro.workspace = true
num.workspace = true
bitvec.workspace = true
colored.workspace = true
usdt.workspace = true
