[package]
name = "sidecar-lite"
version = "0.1.0"
edition = "2021"

[lib]
name = "sidecar_lite"
crate_type = ["dylib"]

[dependencies]
p4rs = { path = "../../p4rs" }
p4-macro = { path = "../../p4-macro" }
num = "0.4"
bitvec = "1.0"
colored = "2.0"
usdt.workspace = true
