[package]
name = "p4-macro-test"
version = "0.1.0"
edition = "2021"

[dependencies]
p4-macro.workspace = true
p4rs.workspace = true
bitvec.workspace = true
colored.workspace = true
usdt.workspace = true
