[package]
name = "p4-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2.workspace = true
syn.workspace = true
p4.workspace = true
p4-rust.workspace = true
serde_tokenstream.workspace = true
serde.workspace = true

[lib]
proc-macro = true
