// Copyright 2022 Oxide Computer Company

//! This is the runtime support create for `x4c` generated programs.
//!
//! The main abstraction in this crate is the [`Pipeline`] trait. Rust code that
//! is generated by `x4c` implements this trait. A `main_pipeline` struct is
//! exported by the generated code that implements [`Pipeline`]. Users can wrap
//! the `main_pipeline` object in harness code to provide higher level
//! interfaces for table manipulation and packet i/o.
//!
//! ```rust
//! use p4rs::{ packet_in, packet_out, Pipeline };
//! use std::net::Ipv6Addr;
//!
//! struct Handler {
//!     pipe: Box<dyn Pipeline>
//! }
//!
//! impl Handler {
//!     /// Create a new pipeline handler.
//!     fn new(pipe: Box<dyn Pipeline>) -> Self {
//!         Self{ pipe }
//!     }
//!
//!     /// Handle a packet from the specified port. If the pipeline produces
//!     /// an output result, send the processed packet to the output port
//!     /// returned by the pipeline.
//!     fn handle_packet(&mut self, port: u16, pkt: &[u8]) {
//!
//!         let mut input = packet_in::new(pkt);
//!
//!         let output =  self.pipe.process_packet(port, &mut input);
//!         for (out_pkt, out_port) in &output {
//!             let mut out = out_pkt.header_data.clone();
//!             out.extend_from_slice(out_pkt.payload_data);
//!             self.send_packet(*out_port, &out);
//!         }
//!
//!     }
//!
//!     /// Add a routing table entry. Packets for the provided destination will
//!     /// be sent out the specified port.
//!     fn add_router_entry(&mut self, dest: Ipv6Addr, port: u16) {
//!         self.pipe.add_table_entry(
//!             "ingress.router.ipv6_routes", // qualified name of the table
//!             "forward_out_port",           // action to invoke on a hit
//!             &dest.octets(),
//!             &port.to_le_bytes(),
//!             0,
//!         );
//!     }
//!
//!     /// Send a packet out the specified port.
//!     fn send_packet(&self, port: u16, pkt: &[u8]) {
//!         // send the packet ...
//!     }
//! }
//! ```
//!
#![allow(incomplete_features)]
#![allow(non_camel_case_types)]

use std::fmt;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

pub use error::TryFromSliceError;
use serde::{Deserialize, Serialize};

use bitvec::prelude::*;

pub mod error;
//pub mod hicuts;
//pub mod rice;
pub mod bitmath;
pub mod checksum;
pub mod externs;
pub mod table;

#[usdt::provider]
mod p4rs_provider {
    fn match_miss(_: &str) {}
}

#[derive(Debug)]
pub struct Bit<'a, const N: usize>(pub &'a [u8]);

impl<'a, const N: usize> Bit<'a, N> {
    //TODO measure the weight of returning TryFromSlice error versus just
    //dropping and incrementing a counter. Relying on dtrace for more detailed
    //debugging.
    pub fn new(data: &'a [u8]) -> Result<Self, TryFromSliceError> {
        let required_bytes = if N & 7 > 0 { (N >> 3) + 1 } else { N >> 3 };
        if data.len() < required_bytes {
            return Err(TryFromSliceError(N));
        }
        Ok(Self(&data[..required_bytes]))
    }
}

impl<const N: usize> fmt::LowerHex for Bit<'_, N> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        for x in self.0 {
            fmt::LowerHex::fmt(&x, f)?;
        }
        Ok(())
    }
}

// TODO more of these for other sizes
impl<'a> From<Bit<'a, 16>> for u16 {
    fn from(b: Bit<'a, 16>) -> u16 {
        u16::from_be_bytes([b.0[0], b.0[1]])
    }
}

// TODO more of these for other sizes
impl std::hash::Hash for Bit<'_, 8> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0[0].hash(state);
    }
}

impl std::cmp::PartialEq for Bit<'_, 8> {
    fn eq(&self, other: &Self) -> bool {
        self.0[0] == other.0[0]
    }
}

impl std::cmp::Eq for Bit<'_, 8> {}

/// Every packet that goes through a P4 pipeline is represented as a `packet_in`
/// instance. `packet_in` objects wrap an underlying mutable data reference that
/// is ultimately rooted in a memory mapped region containing a ring of packets.
#[derive(Debug)]
pub struct packet_in<'a> {
    /// The underlying data. Owned by an external, memory-mapped packet ring.
    pub data: &'a [u8],

    /// Extraction index. Everything before `index` has been extracted already.
    /// Only data after `index` is eligble for extraction. Extraction is always
    /// for contiguous segments of the underlying packet ring data.
    pub index: usize,
}

#[derive(Debug)]
pub struct packet_out<'a> {
    pub header_data: Vec<u8>,
    pub payload_data: &'a [u8],
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TableEntry {
    pub action_id: String,
    pub keyset_data: Vec<u8>,
    pub parameter_data: Vec<u8>,
}

pub trait Pipeline: Send {
    /// Process an input packet and produce a set of output packets. Normally
    /// there will be a single output packet. However, if the pipeline sets
    /// `egress_metadata_t.broadcast` there may be multiple output packets.
    fn process_packet<'a>(
        &mut self,
        port: u16,
        pkt: &mut packet_in<'a>,
    ) -> Vec<(packet_out<'a>, u16)>;

    //TODO use struct TableEntry?
    /// Add an entry to a table identified by table_id.
    fn add_table_entry(
        &mut self,
        table_id: &str,
        action_id: &str,
        keyset_data: &[u8],
        parameter_data: &[u8],
        priority: u32,
    );

    /// Remove an entry from a table identified by table_id.
    fn remove_table_entry(&mut self, table_id: &str, keyset_data: &[u8]);

    /// Get all the entries in a table.
    fn get_table_entries(&self, table_id: &str) -> Option<Vec<TableEntry>>;

    /// Get a list of table ids
    fn get_table_ids(&self) -> Vec<&str>;
}

/// A fixed length header trait.
pub trait Header {
    fn new() -> Self;
    fn size() -> usize;
    fn set(&mut self, buf: &[u8]) -> Result<(), TryFromSliceError>;
    fn set_valid(&mut self);
    fn set_invalid(&mut self);
    fn is_valid(&self) -> bool;
    fn to_bitvec(&self) -> BitVec<u8, Msb0>;
}

impl<'a> packet_in<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self { data, index: 0 }
    }

    // TODO: this function signature is a bit unforunate in the sense that the
    // p4 compiler generates call sites based on a p4 `packet_in` extern
    // definition. But based on that definition, there is no way for the
    // compiler to know that this function returns a result that needs to be
    // interrogated. In fact, the signature for packet_in::extract from the p4
    // standard library requires the return type to be `void`, so this signature
    // cannot return a result without the compiler having special knowledge of
    // functions that happen to be called "extract".
    pub fn extract<H: Header>(&mut self, h: &mut H) {
        //TODO what if a header does not end on a byte boundary?
        let n = H::size();
        let start = if self.index > 0 { self.index >> 3 } else { 0 };
        match h.set(&self.data[start..start + (n >> 3)]) {
            Ok(_) => {}
            Err(e) => {
                //TODO better than this
                println!("packet extraction failed: {}", e);
            }
        }
        self.index += n;
        h.set_valid();
    }

    // This is the same as extract except we return a new header instead of
    // modifying an existing one.
    pub fn extract_new<H: Header>(&mut self) -> Result<H, TryFromSliceError> {
        let n = H::size();
        let start = if self.index > 0 { self.index >> 3 } else { 0 };
        self.index += n;
        let mut x = H::new();
        x.set(&self.data[start..start + (n >> 3)])?;
        Ok(x)
    }
}

//XXX: remove once classifier defined in terms of bitvecs
pub fn bitvec_to_biguint(bv: &BitVec<u8, Msb0>) -> table::BigUintKey {
    let s = bv.as_raw_slice();
    table::BigUintKey {
        value: num::BigUint::from_bytes_le(s),
        width: s.len(),
    }
}

pub fn bitvec_to_ip6addr(bv: &BitVec<u8, Msb0>) -> std::net::IpAddr {
    let mut arr: [u8; 16] = bv.as_raw_slice().try_into().unwrap();
    arr.reverse();
    std::net::IpAddr::V6(std::net::Ipv6Addr::from(arr))
}

#[repr(C, align(16))]
pub struct AlignedU128(pub u128);

pub fn int_to_bitvec(x: i128) -> BitVec<u8, Msb0> {
    //let mut bv = BitVec::<u8, Msb0>::new();
    let mut bv = bitvec![mut u8, Msb0; 0; 128];
    bv.store(x);
    bv
}

pub fn bitvec_to_bitvec16(mut x: BitVec<u8, Msb0>) -> BitVec<u8, Msb0> {
    x.resize(16, false);
    x
}

pub fn dump_bv(x: &BitVec<u8, Msb0>) -> String {
    if x.is_empty() {
        "∅".into()
    } else {
        let v: u128 = x.load_le();
        format!("{:x}", v)
    }
}

pub fn dump_ip4(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 32 {
        return dump_bv(x);
    }
    let v: u32 = x.load_le();
    Ipv4Addr::from(v).to_string()
}

pub fn dump_ip6(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 128 {
        return dump_bv(x);
    }
    let v: u128 = x.load_le();
    Ipv6Addr::from(v).to_string()
}

pub fn dump_mac(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 48 {
        return dump_bv(x);
    }
    let v: u128 = x.load_le();
    format!(
        "{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
        (v >> 40) & 0xff,
        (v >> 32) & 0xff,
        (v >> 24) & 0xff,
        (v >> 16) & 0xff,
        (v >> 8) & 0xff,
        v & 0xff,
    )
}

pub fn dump_ether_type(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 16 {
        return dump_bv(x);
    }
    let v: u16 = x.load_le();
    let name = match v {
        0x0800 => Some("IPv4"),
        0x0806 => Some("ARP"),
        0x0901 => Some("Sidecar"),
        0x8100 => Some("VLAN"),
        0x86dd => Some("IPv6"),
        0x8847 => Some("MPLS unicast"),
        0x8848 => Some("MPLS multicast"),
        0x88a8 => Some("QinQ"),
        _ => None,
    };
    match name {
        Some(n) => format!("0x{:04x} ({})", v, n),
        None => format!("0x{:04x}", v),
    }
}

pub fn dump_ip_proto(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 8 {
        return dump_bv(x);
    }
    let v: u8 = x.load_le();
    let name = match v {
        1 => Some("ICMPv4"),
        6 => Some("TCP"),
        17 => Some("UDP"),
        41 => Some("IPv6-in-IPv4"),
        43 => Some("IPv6-Route"),
        44 => Some("IPv6-Frag"),
        58 => Some("ICMPv6"),
        59 => Some("IPv6-NoNxt"),
        60 => Some("IPv6-Opts"),
        132 => Some("SCTP"),
        _ => None,
    };
    match name {
        Some(n) => format!("0x{:02x} ({})", v, n),
        None => format!("0x{:02x}", v),
    }
}

pub fn dump_tcp_flags(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 8 {
        return dump_bv(x);
    }
    let v: u8 = x.load_le();
    if v == 0 {
        return "none".into();
    }
    let mut flags = Vec::new();
    if v & 0x01 != 0 {
        flags.push("FIN");
    }
    if v & 0x02 != 0 {
        flags.push("SYN");
    }
    if v & 0x04 != 0 {
        flags.push("RST");
    }
    if v & 0x08 != 0 {
        flags.push("PSH");
    }
    if v & 0x10 != 0 {
        flags.push("ACK");
    }
    if v & 0x20 != 0 {
        flags.push("URG");
    }
    if v & 0x40 != 0 {
        flags.push("ECE");
    }
    if v & 0x80 != 0 {
        flags.push("CWR");
    }
    flags.join("|")
}

pub fn dump_arp_op(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 16 {
        return dump_bv(x);
    }
    let v: u16 = x.load_le();
    let name = match v {
        1 => Some("Request"),
        2 => Some("Reply"),
        3 => Some("RARP Request"),
        4 => Some("RARP Reply"),
        _ => None,
    };
    match name {
        Some(n) => format!("0x{:04x} ({})", v, n),
        None => format!("0x{:04x}", v),
    }
}

pub fn dump_icmp_type(x: &BitVec<u8, Msb0>) -> String {
    if x.len() != 8 {
        return dump_bv(x);
    }
    let v: u8 = x.load_le();
    // Types 0-127 use ICMPv4 semantics; types 128-255 are exclusively ICMPv6.
    let name = match v {
        // ICMPv4
        0 => Some("Echo Reply"),
        3 => Some("Dest Unreachable"),
        5 => Some("Redirect"),
        8 => Some("Echo Request"),
        11 => Some("Time Exceeded"),
        12 => Some("Parameter Problem"),
        // ICMPv6 (128+ are unambiguously ICMPv6)
        128 => Some("Echo Request"),
        129 => Some("Echo Reply"),
        130 => Some("MLD Query"),
        131 => Some("MLD Report"),
        132 => Some("MLD Done"),
        133 => Some("RS"),
        134 => Some("RA"),
        135 => Some("NS"),
        136 => Some("NA"),
        137 => Some("Redirect"),
        143 => Some("MLDv2 Report"),
        _ => None,
    };
    match name {
        Some(n) => format!("0x{:02x} ({})", v, n),
        None => format!("0x{:02x}", v),
    }
}

pub fn extract_exact_key(
    keyset_data: &[u8],
    offset: usize,
    len: usize,
) -> table::Key {
    table::Key::Exact(table::BigUintKey {
        value: num::BigUint::from_bytes_le(&keyset_data[offset..offset + len]),
        width: len,
    })
}

pub fn extract_range_key(
    keyset_data: &[u8],
    offset: usize,
    len: usize,
) -> table::Key {
    table::Key::Range(
        table::BigUintKey {
            value: num::BigUint::from_bytes_le(
                &keyset_data[offset..offset + len],
            ),
            width: len,
        },
        table::BigUintKey {
            value: num::BigUint::from_bytes_le(
                &keyset_data[offset + len..offset + len + len],
            ),
            width: len,
        },
    )
}

/// Extract a ternary key from the provided keyset data. Ternary keys come in
/// two parts. The first part is a leading bit that indicates whether we care
/// about the value. If that leading bit is non-zero, the trailing bits of the
/// key are interpreted as a binary value. If the leading bit is zero, the
/// trailing bits are ignored and a Ternary::DontCare key is returned.
pub fn extract_ternary_key(
    keyset_data: &[u8],
    offset: usize,
    len: usize,
) -> table::Key {
    let care = keyset_data[offset];
    if care != 0 {
        table::Key::Ternary(table::Ternary::Value(table::BigUintKey {
            value: num::BigUint::from_bytes_le(
                &keyset_data[offset + 1..offset + 1 + len],
            ),
            width: len,
        }))
    } else {
        table::Key::Ternary(table::Ternary::DontCare)
    }
}

pub fn extract_lpm_key(
    keyset_data: &[u8],
    offset: usize,
    _len: usize,
) -> table::Key {
    let (addr, len) = match keyset_data.len() {
        // IPv4
        5 => {
            let data: [u8; 4] =
                keyset_data[offset..offset + 4].try_into().unwrap();
            (IpAddr::from(data), keyset_data[offset + 4])
        }
        // IPv6
        17 => {
            let data: [u8; 16] =
                keyset_data[offset..offset + 16].try_into().unwrap();
            (IpAddr::from(data), keyset_data[offset + 16])
        }
        x => {
            panic!("lpm: key must be len 5 (ipv4) or 17 (ipv6) found {}", x);
        }
    };

    table::Key::Lpm(table::Prefix { addr, len })
}

#[cfg(test)]
mod tests {
    use super::*;

    // Construct a bitvec as it would appear after header::set() — bytes are
    // reversed for multi-byte fields (>8 bits), unchanged for single-byte fields.
    fn net_bv(bytes: &[u8]) -> BitVec<u8, Msb0> {
        let mut v = bytes.to_vec();
        if v.len() > 1 {
            v.reverse();
        }
        BitVec::<u8, Msb0>::from_vec(v)
    }

    #[test]
    fn test_dump_ip4() {
        assert_eq!(dump_ip4(&net_bv(&[192, 168, 1, 1])), "192.168.1.1");
        assert_eq!(dump_ip4(&net_bv(&[10, 0, 0, 1])), "10.0.0.1");
        assert_eq!(dump_ip4(&net_bv(&[0, 0, 0, 0])), "0.0.0.0");
        assert_eq!(dump_ip4(&net_bv(&[255, 255, 255, 255])), "255.255.255.255");
    }

    #[test]
    fn test_dump_ip6() {
        let mut fd00_1 = [0u8; 16];
        fd00_1[0] = 0xfd;
        fd00_1[15] = 0x01;
        assert_eq!(dump_ip6(&net_bv(&fd00_1)), "fd00::1");

        let mut loopback = [0u8; 16];
        loopback[15] = 1;
        assert_eq!(dump_ip6(&net_bv(&loopback)), "::1");
    }

    #[test]
    fn test_dump_mac() {
        assert_eq!(
            dump_mac(&net_bv(&[0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff])),
            "aa:bb:cc:dd:ee:ff"
        );
        assert_eq!(
            dump_mac(&net_bv(&[0x00, 0x00, 0x00, 0x00, 0x00, 0x00])),
            "00:00:00:00:00:00"
        );
    }

    #[test]
    fn test_dump_ether_type() {
        assert_eq!(dump_ether_type(&net_bv(&[0x08, 0x00])), "0x0800 (IPv4)");
        assert_eq!(dump_ether_type(&net_bv(&[0x08, 0x06])), "0x0806 (ARP)");
        assert_eq!(dump_ether_type(&net_bv(&[0x86, 0xdd])), "0x86dd (IPv6)");
        assert_eq!(dump_ether_type(&net_bv(&[0x09, 0x01])), "0x0901 (Sidecar)");
        assert_eq!(dump_ether_type(&net_bv(&[0x12, 0x34])), "0x1234");
    }

    #[test]
    fn test_dump_ip_proto() {
        assert_eq!(dump_ip_proto(&net_bv(&[1])), "0x01 (ICMPv4)");
        assert_eq!(dump_ip_proto(&net_bv(&[6])), "0x06 (TCP)");
        assert_eq!(dump_ip_proto(&net_bv(&[17])), "0x11 (UDP)");
        assert_eq!(dump_ip_proto(&net_bv(&[58])), "0x3a (ICMPv6)");
        assert_eq!(dump_ip_proto(&net_bv(&[99])), "0x63");
    }

    #[test]
    fn test_dump_tcp_flags() {
        assert_eq!(dump_tcp_flags(&net_bv(&[0x00])), "none");
        assert_eq!(dump_tcp_flags(&net_bv(&[0x02])), "SYN");
        assert_eq!(dump_tcp_flags(&net_bv(&[0x12])), "SYN|ACK");
        assert_eq!(dump_tcp_flags(&net_bv(&[0x01])), "FIN");
        assert_eq!(dump_tcp_flags(&net_bv(&[0x04])), "RST");
        assert_eq!(
            dump_tcp_flags(&net_bv(&[0xff])),
            "FIN|SYN|RST|PSH|ACK|URG|ECE|CWR"
        );
    }

    #[test]
    fn test_dump_arp_op() {
        assert_eq!(dump_arp_op(&net_bv(&[0x00, 0x01])), "0x0001 (Request)");
        assert_eq!(dump_arp_op(&net_bv(&[0x00, 0x02])), "0x0002 (Reply)");
        assert_eq!(dump_arp_op(&net_bv(&[0x00, 0x05])), "0x0005");
    }

    #[test]
    fn test_dump_icmp_type() {
        assert_eq!(dump_icmp_type(&net_bv(&[0])), "0x00 (Echo Reply)");
        assert_eq!(dump_icmp_type(&net_bv(&[8])), "0x08 (Echo Request)");
        assert_eq!(dump_icmp_type(&net_bv(&[133])), "0x85 (RS)");
        assert_eq!(dump_icmp_type(&net_bv(&[134])), "0x86 (RA)");
        assert_eq!(dump_icmp_type(&net_bv(&[135])), "0x87 (NS)");
        assert_eq!(dump_icmp_type(&net_bv(&[136])), "0x88 (NA)");
        assert_eq!(dump_icmp_type(&net_bv(&[50])), "0x32");
    }
}

pub fn extract_bool_action_parameter(
    parameter_data: &[u8],
    offset: usize,
) -> bool {
    parameter_data[offset] == 1
}

pub fn extract_bit_action_parameter(
    parameter_data: &[u8],
    offset: usize,
    size: usize,
) -> BitVec<u8, Msb0> {
    let mut byte_size = size >> 3;
    if !size.is_multiple_of(8) {
        byte_size += 1;
    }
    let mut b: BitVec<u8, Msb0> =
        BitVec::from_slice(&parameter_data[offset..offset + byte_size]);
    b.resize(size, false);
    b
}
