[book]
authors = ["Ryan Goodfellow"]
language = "en"
multilingual = false
src = "src"
title = "The x4c Book"

[output.html]
additional-css = ["./theme/highlight.css"]

[output.html.playground]
runnable = false
