[package]
name = "p4-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
p4.workspace = true
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true
prettyplease.workspace = true
tempfile.workspace = true
